server:
  port: 9090

spring:
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:todoapi
    username: todo_api
    password:
  jpa:
    properties:
      hibernate:
        show_sql: true
        use_sql_comment: true
        format_sql: true
        type: trace

